version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.17-alpine
  working_dir: /gam
  restart: always
  volumes:
    - .:/gam:cached
    - ./node_modules:/gam/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  graphql:
    <<: *node
    working_dir: /gam/services/graphql
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      JSON_KEY_FILE_PATH: ${JSON_KEY_FILE_PATH-/gam/services/graphql/service-account.json}
      NETWORK_CODE: ${NETWORK_CODE}
      VERSION: v202408
    ports:
      - "26790:26790"

volumes:
  yarn-cache: {}
